version: '3'
services:
  my-sql-server:
    container_name: my-sql-server
    image: mysql-db:latest
    ports:
      - 3306:3306
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  crud-api-deploy:
    container_name: crud-api-deploy
    image: crud-api-deploy:latest
    ports:
      - 8080:8080
    environment:
      - DATABASE_URL=jdbc:mysql://my-sql-server:3306/example_database
      - DATABASE_USERNAME=gagan
      - DATABASE_PASSWORD=@gagan123
    depends_on:
      my-sql-server:
        condition: service_healthy
    links:
      - my-sql-server:mysql